version: '3.7'

volumes:
  prometheus_data:

networks:
  prom:

services:

  # https://github.com/prometheus/node_exporter
  # https://github.com/prometheus/pushgateway
  prometheus:
    image: prom/prometheus:v2.18.1
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - prom
    restart: always

  prom-pushgateway:
    image: prom/pushgateway
    ports:
      - 9091:9091
    networks:
      - prom
    restart: always